{% set version = "6.0.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-v8
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/V8_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/V8/V8_{{ version }}.tar.gz
  sha256: 696d581f25dace004a8e8cb39b7fe8c30be4497d8907548f44cf3222d761bfb6

build:
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-curl                       # [build_platform != target_platform]
    - r-jsonlite                   # [build_platform != target_platform]    
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.12
    - r-curl >=1.0
    - r-jsonlite >=1.0
    - libv8  # [not win]
    - icu
  run:
    - r-base
    - r-rcpp >=0.12.12
    - r-curl >=1.0
    - r-jsonlite >=1.0

test:
  commands:
    - $R -e "library('V8')"           # [not win]
    - "\"%R%\" -e \"library('V8')\""  # [win]

about:
  home: https://v8.dev
  dev_url: https://github.com/jeroen/v8
  license: MIT
  summary: An R interface to V8, Google's open source JavaScript and WebAssembly engine. This package can be compiled either with V8 version 6 and up, a NodeJS shared library, or the legacy 3.14/3.15 branch of V8.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - xhochy
