{% set version = "3.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-v8
  version: {{ version|replace("-", "_") }}

source:
  url:  # [not win]
    - {{ cran_mirror }}/src/contrib/V8_{{ version }}.tar.gz  # [not win]
    - {{ cran_mirror }}/src/contrib/Archive/V8/V8_{{ version }}.tar.gz  # [not win]
  sha256: f5c8a2a03cc1be9f504f47711a0fcd1b962745139c9fb2a10fbd79c4ae103fbd  # [not win]

  url: https://cran.r-project.org/bin/windows/contrib/{{ r_base[0:3] }}/V8_{{ version }}.zip  # [win]
  sha256: 3755bc47afb4cf7439e236992017f2c837f05ecc94ba2b25cb84cb954e4cf001  # [win and r_base=="4.0"]

build:
  merge_build_host: true  # [win]
  number: 0
  skip: True  # [win and r_base=="3.6"]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - {{ posix }}autoconf  # [not win]
    - {{ posix }}automake  # [not win]
    - {{ posix }}pkg-config  # [not win]
    - {{ posix }}make  # [not win]
  host:
    - r-base
    - r-rcpp >=0.12.12
    - r-curl >=1.0
    - r-jsonlite >=1.0
    - libv8  # [not win]
    - icu
  run:
    - r-base
    - {{ native }}gcc-libs  # [win]
    - r-rcpp >=0.12.12
    - r-curl >=1.0
    - r-jsonlite >=1.0

test:
  commands:
    - $R -e "library('V8')"           # [not win]
    - "\"%R%\" -e \"library('V8')\""  # [win]

about:
  home: https://github.com/jeroen/v8 (devel) https://v8.dev (upstream)
  license: MIT
  summary: An R interface to Google's open source JavaScript engine. This  package can now be compiled either with V8 version 6 or 7 (LTS) from  nodejs or with the legacy 3.14/3.15 branch of V8.
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - xhochy

# Package: V8
# Type: Package
# Title: Embedded JavaScript Engine for R
# Version: 2.3
# Authors@R: person("Jeroen", "Ooms", role = c("aut", "cre"), email = "jeroen@berkeley.edu", comment = c(ORCID = "0000-0002-4035-0289"))
# Description: An R interface to Google's open source JavaScript engine. This  package can now be compiled either with V8 version 6 or 7 (LTS) from  nodejs or with the legacy 3.14/3.15 branch of V8.
# License: MIT + file LICENSE
# URL: https://github.com/jeroen/v8 (devel) https://v8.dev (upstream)
# BugReports: https://github.com/jeroen/v8/issues
# SystemRequirements: V8 version 6 or 7 is recommended, but 3.14 (legacy) is still supported as well. On Debian / Ubuntu you need either libv8-dev or libnode-dev, on Fedora use v8-devel.
# NeedsCompilation: yes
# VignetteBuilder: knitr
# Imports: Rcpp (>= 0.12.12), jsonlite (>= 1.0), curl (>= 1.0), utils
# LinkingTo: Rcpp
# Suggests: testthat, knitr, rmarkdown
# RoxygenNote: 6.1.1
# Language: en-US
# Packaged: 2019-07-02 09:56:44 UTC; jeroen
# Author: Jeroen Ooms [aut, cre] (<https://orcid.org/0000-0002-4035-0289>)
# Maintainer: Jeroen Ooms <jeroen@berkeley.edu>
# Repository: CRAN
# Date/Publication: 2019-07-02 10:51:07 UTC
