appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: aQhd7+J03VDtywM09Xr4TynV0xpHHkQRqHNBbj9842CKmbc9oc13tFc9Y5I+jMOlHPSvrK7wzlCvpUo2ve/DgJPOUuRKmT3a65PfT6vZXIIm+2BLVYpBm124A5n9++tGF6nLwJs5uo9T7CbbXfZF3EwkitywaPTFTIqHf/qwgtoOZpFc+2U1cBv11P0Reyb2hqjEenaACfbEpDJ070wroPTyWYXXYFVPRbFjsqJT6XCvxYbzMSDJ3wr/LFupSFC9qzFUC2NSNtXl7sib36JEMSsksHCSilWyRqgBXIRsrCYpXOncVVWpbDy+GAwWTylBrwPQhvn5gYyESU3gwOtycp7eHmDRjrZcXtOtfjgbCMRh7UYt0JbOofbK4y+PoJvR/p0qOfnl6WAydcQSonCxuVUeqUs8dC9kkd5trYd6QKsnbkCq7UvMKhpeThuKJu6n2CNOr0BUyRozvfps7LSCkRnBjxdv+x1YPv/wcZcKBFnV2mvFJHlIjO+sulmBZHZFWToR+DIsUAVbsuuyw+gX8YGlkLt+d0lizJ8Pr15ttZkXekPSrnU7sUFftFkIYZJScTNnZiZpoEzAH+WvQAUjTBrs6scaWoMQscqgOix0pp+9Q4zvj1BStFzOWeyQhkib6wwl3xUgs8uiwTkKg/6PhYh37uqGd4cziNWN1iMLckw=
conda_forge_output_validation: true
